import test from 'node:test';
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { parseHTML } from 'linkedom';
import { mkdir } from 'node:fs/promises';

test('explicit planning retains original and per-mode results; switching never requests again',async()=>{
  const {window}=parseHTML('<html><body><div id="root"></div></body></html>');
  Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});
  await mkdir('.openai',{recursive:true});
  await build({entryPoints:['modules/guidance/NavigationStart.tsx'],outfile:'.openai/navigation-preview-check.mjs',bundle:true,platform:'node',format:'esm',packages:'external',jsx:'automatic',loader:{'.css':'empty'},plugins:[{name:'preview-fixtures',setup(b){
    b.onResolve({filter:/navigation\/provider$/},()=>({path:'planner',namespace:'test'}));
    b.onResolve({filter:/(RouteViews|RouteMiniMap|RouteElevationSummary|useRouteDialogFocus)$/},a=>({path:a.path.split('/').at(-1),namespace:'test'}));
    b.onLoad({filter:/.*/,namespace:'test'},a=>({resolveDir:process.cwd(),contents: a.path==='planner' ? `export const planRoute=(...args)=>globalThis.previewPlanner(...args);` : a.path==='RouteViews' ? `import React from 'react';export const RouteBack=({onBack})=>React.createElement('button',{onClick:onBack},'返回');` : a.path==='RouteMiniMap' ? `import React from 'react';export const RouteMiniMap=({coordinates,routes,selectedId})=>React.createElement('output',{'data-preview':true,'data-count':routes.length,'data-selected':selectedId},JSON.stringify(coordinates));` : a.path==='useRouteDialogFocus' ? `export const useRouteDialogFocus=()=>null;` : `export const RouteElevationSummary=()=>null;` }));
  }}]});
  const React=await import('react'),{act}=React,{createRoot}=await import('react-dom/client');
  const {NavigationStart}=await import('../.openai/navigation-preview-check.mjs');
  const {trackNavigation}=await import('../modules/guidance/savedRoute.ts');
  const track={id:'original',name:'原始手绘',createdAt:1,segments:[[[103,30],[103.001,30.003],[103.005,30.006]]]};
  const target=trackNavigation(track,1);const original=JSON.stringify(target);
  let requests=[],started=[];globalThis.previewPlanner=(start,end,mode,signal)=>new Promise((resolve,reject)=>requests.push({start,end,mode,signal,resolve,reject}));
  const root=createRoot(document.getElementById('root'));
  await act(async()=>root.render(React.createElement(NavigationStart,{target,onStart:t=>started.push(t),onClose(){}})));
  const button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent===text);
  assert.equal(requests.length,0);
  assert.equal(button('沿原路线开始导航').disabled,false);
  assert.equal(document.querySelector('[data-preview]').getAttribute('data-count'),'1');
  await act(async()=>button('骑行').click());assert.equal(requests.length,0);
  await act(async()=>button('规划此方式').click());assert.equal(requests[0].mode,'bicycle');
  const route={...target.route,geometryKind:'road',mode:'bicycle',coordinates:[[103,30],[103.003,30.001],[103.005,30.006]],distance:1000};
  await act(async()=>requests[0].resolve(route));
  assert.equal(document.querySelector('[data-preview]').getAttribute('data-count'),'2');
  await act(async()=>button('驾车').click());assert.equal(requests.length,1);
  await act(async()=>button('规划此方式').click());
  await act(async()=>requests[1].resolve({...route,mode:'auto',distance:1200}));
  assert.equal(document.querySelector('[data-preview]').getAttribute('data-count'),'3');
  await act(async()=>button('骑行').click());assert.equal(requests.length,2);
  await act(async()=>button('使用新规划开始导航').click());assert.equal(started[0].route.mode,'bicycle');
  await act(async()=>button('重新规划').click());assert.equal(requests.length,3);
  await act(async()=>requests[2].reject(Error('服务不可用')));
  assert.equal(document.querySelector('footer button').disabled,false);
  await act(async()=>button('步行').click());await act(async()=>button('规划此方式').click());
  await act(async()=>button('骑行').click());assert.equal(requests[3].signal.aborted,true);
  await act(async()=>requests[3].resolve({...route,mode:'pedestrian'}));
  assert.equal(document.querySelector('[data-preview]').getAttribute('data-count'),'3');
  await act(async()=>button('原始路线').click());
  await act(async()=>button('沿原路线开始导航').click());assert.equal(started.at(-1).route.geometryKind,'track');
  assert.equal(JSON.stringify(target),original);
  await act(async()=>root.render(null));
  await act(async()=>root.render(React.createElement(NavigationStart,{target:{...target,route:{...target.route,createdAt:999}},onStart(){},onClose(){}})));
  await act(async()=>button('骑行').click());assert.equal(requests.length,4);assert.equal(document.querySelector('footer button').disabled,false);
  await act(async()=>root.render(null));
  const roadStart={name:'西端',coordinates:[102.9,29.9]},roadEnd={name:'东端',coordinates:[103.2,30.2]};
  const roadTarget={id:'road-original',name:'道路原路线',savedAt:2,start:roadStart,end:roadEnd,route:{mode:'auto',coordinates:[roadStart.coordinates,[103.04,30.06],roadEnd.coordinates],distance:42000,duration:3600,steps:[{instruction:'向右转 · 旧道路',distance:42000,duration:3600,elapsedSeconds:0,coordinates:[roadStart.coordinates,[103.04,30.06],roadEnd.coordinates]}],snapped:[roadStart.coordinates,roadEnd.coordinates],stops:[roadStart,roadEnd],roadLegs:[[roadStart.coordinates,[103.04,30.06],roadEnd.coordinates]],segments:[{kind:'road',coordinates:[roadStart.coordinates,[103.04,30.06],roadEnd.coordinates]}],createdAt:2}};
  await act(async()=>root.render(React.createElement(NavigationStart,{target:roadTarget,onStart:t=>started.push(t),onClose(){}})));
  assert.equal(requests.length,4);
  await act(async()=>button('⇅ 交换').click());
  assert.equal(requests.length,4,'reversing the original road route must not request a new plan');
  assert.deepEqual(JSON.parse(document.querySelector('[data-preview]').textContent),[roadEnd.coordinates,[103.04,30.06],roadStart.coordinates]);
  assert.match(document.querySelector('.route-note').textContent,/驾车请点“驾车”重新规划/);
  assert.equal(button('沿反向原路线开始导航').disabled,false);
  await act(async()=>button('沿反向原路线开始导航').click());
  assert.deepEqual(started.at(-1).start,roadEnd);
  assert.deepEqual(started.at(-1).end,roadStart);
  assert.deepEqual(started.at(-1).route.coordinates,[roadEnd.coordinates,[103.04,30.06],roadStart.coordinates]);
  await act(async()=>root.unmount());delete globalThis.previewPlanner;
});
