import test from 'node:test';
import assert from 'node:assert/strict';
import {parseOvobj} from '../modules/dataTransfer/ovobjImport.ts';
import {parseFile} from '../modules/dataTransfer/fileImport.ts';

function frame(payload,first=[2964382651n,10028826714n],count=5){
  const name=Buffer.from('sample'),body=Buffer.alloc(100+1+name.length+1+4+8+16+payload.length);
  body.writeUInt32LE(103);body[100]=name.length;name.copy(body,101);
  let i=101+name.length+5;body.writeBigInt64LE(BigInt(count),i);i+=8;body.writeBigInt64LE(first[0],i);body.writeBigInt64LE(first[1],i+8);payload.copy(body,i+16);
  const file=Buffer.alloc(328+body.length);file.write('OviO');file.writeUInt32LE(105,12);file.writeBigInt64LE(BigInt(file.length),24);
  file.writeUInt32LE(31,244);file.writeBigInt64LE(BigInt(file.length-264),248);file.writeUInt32LE(body.length,280);file.writeUInt32LE(8,284);body.copy(file,328);return file;
}
// Independent paired OVOBJ/OVJSN example, not generated by our decoder.
// https://github.com/Fangster-1/ovkml-converter/tree/master/tests/fixtures
const publicDelta=Buffer.from('980f40c81f0a0b183e5f9203893f583b66f801d563580b26a0103d6d','hex');
test('OVOBJ packed deltas match independently exported coordinates including both signs',async()=>{
  const file=frame(publicDelta),r=await parseFile(new File([file],'sample.ovobj'),'cgcs2000');
  assert.deepEqual(r.tracks[0].segments[0],[[100.28826714,29.64382651],[100.30860901,29.63882839],[100.31092644,29.65926688],[100.30972481,29.6787318],[100.2990818,29.68238572]]);
  assert.equal(r.tracks[0].name,'sample');assert.equal(r.importWarnings,undefined);
  assert.equal(r.tracks[0].importFormat,'OVOBJ');assert.equal(r.tracks[0].samples,undefined);
  assert.match(parseOvobj(file,'sample.ovobj','auto').importWarnings[0],/WGS84/);
});
test('OVOBJ validates count, exact byte end, revision and frame length instead of scanning coordinate-like bytes',()=>{
  const good=frame(publicDelta);
  for(const mutate of [b=>b.writeUInt32LE(106,12),b=>b.writeUInt32LE(7,284),b=>b.writeUInt32LE(9999,280),b=>b.writeUInt32LE(102,328),b=>b.writeBigInt64LE(4n,440)]){
    const bad=Buffer.from(good);mutate(bad);assert.throws(()=>parseOvobj(bad,'a.ovobj','auto'));
  }
  assert.throws(()=>parseOvobj(good.subarray(0,-1),'a.ovobj','auto'));
  assert.throws(()=>parseOvobj(frame(publicDelta,undefined,6001),'a.ovobj','auto'),/6000/);
});
test('OVOBJ tiny zero deltas and negative initial hemisphere are decoded within frame bounds',()=>{
  const r=parseOvobj(frame(Buffer.from([0,0]),[-3000000000n,-7300000000n],3),'a.ovobj','cgcs2000');
  assert.deepEqual(r.tracks[0].segments[0],[[-73,-30],[-73,-30],[-73,-30]]);
});
