import json
from pathlib import Path
p=Path('output/geology-drill-demo')
data=json.loads((p/'zk0003-data.json').read_text(encoding='utf-8'))
blob=json.dumps(data,ensure_ascii=False,separators=(',',':')).replace('<','\\u003c')
html=r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ZK0003 钻孔示图预览</title>
<style>
:root{color-scheme:light;--ink:#21313d;--muted:#61717e;--line:#d5dee4;--paper:#f4f7f8;--accent:#167d83}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.5 "Microsoft YaHei",system-ui,sans-serif}.top{padding:18px 22px 14px;background:#fff;border-bottom:1px solid var(--line)}h1{font-size:20px;margin:0 0 7px}.notice{color:#425560;max-width:1120px}.notice b{color:#9a5e17}.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:13px}.group{display:flex;gap:6px;border-right:1px solid var(--line);padding-right:10px;margin-right:2px}button,a.btn{appearance:none;border:1px solid #c4d0d7;background:white;color:#243743;border-radius:7px;padding:7px 11px;font:inherit;text-decoration:none;cursor:pointer}button:hover,a.btn:hover{border-color:var(--accent);color:var(--accent)}button.active{background:#e3f1f0;border-color:var(--accent);color:#12676b}.layout{height:calc(100vh - 157px);min-height:400px;padding:12px 16px}.frame{height:100%;overflow:auto;background:#fff;border:1px solid var(--line);border-radius:9px;box-shadow:0 2px 8px #1937440b}.frame svg{display:block;margin:0 auto}.foot{color:var(--muted);font-size:12px;padding:6px 22px}.pill{border-radius:99px;background:#edf2f4;padding:3px 8px;color:#536670}.download{background:#176f76!important;color:white!important;border-color:#176f76!important}.download:hover{background:#105c62!important;color:#fff!important}.small{font-size:12px;color:var(--muted)}@media(max-width:700px){.top{padding:14px}.layout{height:calc(100vh - 220px);padding:8px}.actions{gap:6px}.group{padding-right:6px}.foot{padding:5px 14px}}
</style></head><body>
<header class="top"><h1>ZK0003 钻孔柱状示图</h1><div class="notice">数据采用底稿未校正孔深，终孔 <b>382.79 m</b>。第 1、4、5 层使用参考花纹示意，其余 20 层待确认；Au、Pb、Zn 无分析结果。孔径仅显示底稿记录的深度点，不代表全孔孔径。</div>
<div class="actions"><div class="group"><button id="full">完整图</button><button id="detail">0–45 m 详图</button></div><div class="group"><button id="fit">适合窗口</button><button id="actual">实际大小</button><button id="minus">−</button><button id="plus">＋</button><span id="zoom" class="pill">100%</span></div><div class="group"><button class="download" id="svgFull">下载完整SVG</button><button class="download" id="pngFull">完整图高清PNG</button></div><div class="group"><button class="download" id="svgDetail">下载详图SVG</button><button class="download" id="pngDetail">详图高清PNG</button></div><a class="btn" href="drawing-data.html">查看附表</a></div></header>
<main class="layout"><div class="frame" id="frame"></div></main><div class="foot">纵向为沿孔量取的孔深；显示比例随窗口缩放。分层描述保留底稿原文，分层段长不代表真厚度。</div>
<script id="sourceData" type="application/json">DATA_SLOT</script><script>
const D=JSON.parse(document.getElementById('sourceData').textContent);let mode='full',scale=1;const frame=document.getElementById('frame'),zoom=document.getElementById('zoom');const W=1160, topY=90, px=6.4, end=D.meta.endpoint_m, fullH=topY+end*px+100;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function y(d){return topY+d*px}function fmt(v){return Number(v).toFixed(2)}
function pattern(id){if(id===1)return '<pattern id="p1" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M-2 10L10-2M4 12L12 4" stroke="#576875" stroke-width="1"/></pattern>';if(id===4)return '<pattern id="p4" width="9" height="9" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1.15" fill="#596d78"/><circle cx="7" cy="7" r="1.15" fill="#596d78"/></pattern>';if(id===5)return '<pattern id="p5" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M0 0L10 10M10 0L0 10" stroke="#65747e" stroke-width=".8"/></pattern>';return ''}
function svgMarkup(which){let detail=which==='detail',min=0,max=detail?45:end,H=detail?topY+max*px+45:fullH;let zTop=detail?topY:0, vbY=detail?0:0;let chunks=[];chunks.push(`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 ${vbY} ${W} ${H}" role="img" aria-label="ZK0003 钻孔柱状图 ${detail?'0至45米详图':'完整图'}"><defs>${[1,4,5].map(pattern).join('')}</defs><rect width="100%" height="100%" fill="white"/><style>text{font-family:'Microsoft YaHei',sans-serif;fill:#263842}.muted{fill:#687a84}.thin{stroke:#aebbc2;stroke-width:1}.grid{stroke:#e5eaed;stroke-width:1;stroke-dasharray:3 4}</style><text x="48" y="32" font-size="20" font-weight="700">ZK0003 钻孔柱状示图</text><text x="48" y="54" font-size="12" class="muted">底稿未校正孔深 · 终孔 ${fmt(end)} m · ${detail?'0–45 m 详图':'完整孔段'}</text>`);
// Header labels
const cols=[[85,'孔深 (m)'],[225,'分层描述 / 花纹'],[450,'回次'],[565,'样品区间'],[790,'孔径点']];for(const [x,t] of cols)chunks.push(`<text x="${x}" y="78" font-size="12" font-weight="600">${t}</text>`);
for(let d=Math.ceil(min/5)*5;d<=max;d+=5){let yy=y(d);chunks.push(`<line x1="95" y1="${yy}" x2="1080" y2="${yy}" class="${d%10===0?'grid':'thin'}"/><text x="85" y="${yy-3}" text-anchor="end" font-size="10" class="muted">${d}</text>`)}
// Layers
for(const l of D.layers){if(l.bottom_m<min||l.top_m>max)continue;let a=Math.max(l.top_m,min),b=Math.min(l.bottom_m,max),yy=y(a),hh=Math.max(1,(b-a)*px),pid=[1,4,5].includes(l.id)?`url(#p${l.id})`:'#f4f6f7';chunks.push(`<rect x="185" y="${yy}" width="198" height="${hh}" fill="${pid}" stroke="#697b84" stroke-width=".8"/><text x="190" y="${yy+Math.min(14,hh/2+4)}" font-size="10" font-weight="600">${l.id} · ${fmt(a)}–${fmt(b)} m</text>`);if(hh>12)chunks.push(`<text x="390" y="${yy+Math.min(13,hh-2)}" font-size="10">${esc(l.description||'（空）')}</text>`);}
// Turn core recoveries
chunks.push('<rect x="430" y="'+y(min)+'" width="46" height="'+((max-min)*px)+'" fill="#f2f4f5" stroke="#82919a"/>');for(const t of D.turns){let a=t.top_m,b=t.bottom_m;if(b<min||a>max)continue;a=Math.max(a,min);b=Math.min(b,max);let yy=y(a),hh=Math.max(1,(b-a)*px),ratio=t.advance_m?Math.min(1,t.core_m/t.advance_m):0;chunks.push(`<rect x="431" y="${yy}" width="44" height="${hh}" fill="#dce5e8" stroke="#71848d" stroke-width=".55"/><rect x="431" y="${yy}" width="${44*ratio}" height="${hh}" fill="#748b96" opacity=".88"/>`)}
// Samples preserve original hole-depth order
chunks.push(`<rect x="525" y="${y(min)}" width="82" height="${(max-min)*px}" fill="#fff" stroke="#a4b1b8"/>`);for(const s of D.samples){if(s.bottom_m<min||s.top_m>max)continue;let a=Math.max(s.top_m,min),b=Math.min(s.bottom_m,max),yy=y(a),hh=Math.max(2,(b-a)*px);chunks.push(`<rect x="527" y="${yy}" width="78" height="${hh}" fill="#e7c58c" stroke="#98713b" stroke-width=".7"/><text x="610" y="${yy+Math.min(10,hh)}" font-size="9">${esc(s.id)}</text>`)}
// single structure depth point only
for(const st of D.structures){if(st.depth_m<min||st.depth_m>max)continue;const yy=y(st.depth_m);chunks.push(`<circle cx="790" cy="${yy}" r="4" fill="#176f76"/><text x="802" y="${yy+4}" font-size="10">${fmt(st.depth_m)} m · ${st.diameter_mm} mm（记录点）</text>`)}
chunks.push(`<text x="185" y="${y(max)+28}" font-size="10" class="muted">层数：实际 ${D.meta.actual_layer_count} 条；基本数据声明 ${D.meta.declared_layer_count} 条。样品区间按底稿深度定位，图形不表示矿化等级。</text></svg>`);return chunks.join('')}
function render(){const svg=svgMarkup(mode);frame.innerHTML=svg;const node=frame.querySelector('svg');const sw=node.viewBox.baseVal.width,sh=node.viewBox.baseVal.height;node.style.width=(sw*scale)+'px';node.style.height=(sh*scale)+'px';zoom.textContent=Math.round(scale*100)+'%'}function setMode(m){mode=m;scale=1;render();frame.scrollTop=0;frame.scrollLeft=0}document.getElementById('full').onclick=()=>setMode('full');document.getElementById('detail').onclick=()=>setMode('detail');document.getElementById('fit').onclick=()=>{let svg=frame.querySelector('svg');scale=Math.min((frame.clientWidth-20)/svg.viewBox.baseVal.width,(frame.clientHeight-20)/svg.viewBox.baseVal.height);render()};document.getElementById('actual').onclick=()=>{scale=1;render()};document.getElementById('plus').onclick=()=>{scale=Math.min(4,scale*1.2);render()};document.getElementById('minus').onclick=()=>{scale=Math.max(.2,scale/1.2);render()};
function saveBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}function saveSvg(which){saveBlob(new Blob([svgMarkup(which)],{type:'image/svg+xml;charset=utf-8'}),which==='full'?'ZK0003-完整示图.svg':'ZK0003-0至45米详图.svg')}function savePng(which){const txt=svgMarkup(which),blob=new Blob([txt],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const k=Math.min(3,12000/img.width,12000/img.height,Math.sqrt(64000000/(img.width*img.height)));const c=document.createElement('canvas');c.width=Math.floor(img.width*k);c.height=Math.floor(img.height*k);const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{if(b)saveBlob(b,which==='full'?'ZK0003-完整示图-高清.png':'ZK0003-0至45米详图-高清.png');URL.revokeObjectURL(url)},'image/png')};img.onerror=()=>{URL.revokeObjectURL(url);alert('PNG生成失败，请下载SVG查看。')};img.src=url}document.getElementById('svgFull').onclick=()=>saveSvg('full');document.getElementById('pngFull').onclick=()=>savePng('full');document.getElementById('svgDetail').onclick=()=>saveSvg('detail');document.getElementById('pngDetail').onclick=()=>savePng('detail');window.addEventListener('resize',()=>{if(scale<1)render()});setMode('full');
</script></body></html>'''.replace('DATA_SLOT',blob)
(p/'index.html').write_text(html,encoding='utf-8')
