from pathlib import Path
p=Path('output/geology-drill-demo/index.html')
html='''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ZK0003 钻孔示图预览</title>
<style>:root{color-scheme:light;--ink:#21313d;--muted:#61717e;--line:#d5dee4;--paper:#f4f7f8;--accent:#167d83}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.5 "Microsoft YaHei",system-ui,sans-serif}.top{padding:18px 22px 14px;background:#fff;border-bottom:1px solid var(--line)}h1{font-size:20px;margin:0 0 7px}.notice{color:#425560;max-width:1120px}.notice b{color:#9a5e17}.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:13px}.group{display:flex;gap:6px;border-right:1px solid var(--line);padding-right:10px;margin-right:2px}button,a.btn{appearance:none;border:1px solid #c4d0d7;background:white;color:#243743;border-radius:7px;padding:7px 11px;font:inherit;text-decoration:none;cursor:pointer}button:hover,a.btn:hover{border-color:var(--accent);color:var(--accent)}button.active{background:#e3f1f0;border-color:var(--accent);color:#12676b}.layout{height:calc(100vh - 157px);min-height:400px;padding:12px 16px}.frame{height:100%;overflow:auto;background:#fff;border:1px solid var(--line);border-radius:9px;box-shadow:0 2px 8px #1937440b}.frame svg{display:block;margin:0 auto}.foot{color:var(--muted);font-size:12px;padding:6px 22px}.pill{border-radius:99px;background:#edf2f4;padding:3px 8px;color:#536670}.download{background:#176f76!important;color:white!important;border-color:#176f76!important}.download:hover{background:#105c62!important;color:#fff!important}.status{font-size:12px;color:#536670;margin-left:4px}@media(max-width:700px){.top{padding:14px}.layout{height:calc(100vh - 220px);padding:8px}.actions{gap:6px}.group{padding-right:6px}.foot{padding:5px 14px}}</style></head><body>
<header class="top"><h1>ZK0003 钻孔柱状示图</h1><div class="notice">数据采用底稿未校正孔深，终孔 <b>382.79 m</b>。第 1、4、5 层使用参考花纹示意，其余 20 层待确认；Au、Pb、Zn 无分析结果。孔径仅显示底稿记录的深度点，不代表全孔孔径。</div><div class="actions"><div class="group"><button id="full">完整图</button><button id="detail">0–45 m 详图</button></div><div class="group"><button id="fit">适合窗口</button><button id="actual">实际大小</button><button id="minus">−</button><button id="plus">＋</button><span id="zoom" class="pill">100%</span></div><div class="group"><button class="download" id="svgFull">下载完整SVG</button><button class="download" id="pngFull">完整图高清PNG</button></div><div class="group"><button class="download" id="svgDetail">下载详图SVG</button><button class="download" id="pngDetail">详图高清PNG</button></div><a class="btn" href="drawing-data.html">查看附表</a><span class="status" id="status">读取示图…</span></div></header>
<main class="layout"><div class="frame" id="frame"></div></main><div class="foot">纵向为沿孔量取的孔深；显示比例随窗口缩放。分层描述保留底稿原文，分层段长不代表真厚度。</div>
<script>
const FILES=Object.freeze({full:'ZK0003-完整示图.svg',detail:'ZK0003-0至45米详图.svg'});let mode='full',scale=1,svgMarkup='',vb={width:1,height:1};const frame=document.getElementById('frame'),zoom=document.getElementById('zoom'),status=document.getElementById('status');
function setStatus(t){status.textContent=t}function setActive(){document.getElementById('full').classList.toggle('active',mode==='full');document.getElementById('detail').classList.toggle('active',mode==='detail')}
async function loadView(m){if(!Object.hasOwn(FILES,m))return;mode=m;scale=1;setActive();setStatus('读取最新SVG…');try{const r=await fetch(FILES[m],{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);const source=await r.text();const doc=new DOMParser().parseFromString(source,'image/svg+xml');const svg=doc.documentElement;if(svg.localName!=='svg'||doc.querySelector('parsererror'))throw Error('SVG格式无效');const box=svg.viewBox.baseVal;if(!box||!box.width||!box.height)throw Error('SVG缺少有效viewBox');vb={width:box.width,height:box.height};svgMarkup=new XMLSerializer().serializeToString(svg);const imported=document.importNode(svg,true);frame.replaceChildren(imported);renderSize();setStatus('已载入 '+FILES[m])}catch(e){frame.replaceChildren();svgMarkup='';setStatus('读取失败：请通过同源静态预览打开；'+e.message)}}
function renderSize(){const s=frame.querySelector('svg');if(!s)return;s.style.width=(vb.width*scale)+'px';s.style.height=(vb.height*scale)+'px';zoom.textContent=Math.round(scale*100)+'%'}document.getElementById('full').onclick=()=>loadView('full');document.getElementById('detail').onclick=()=>loadView('detail');document.getElementById('fit').onclick=()=>{scale=Math.min((frame.clientWidth-20)/vb.width,(frame.clientHeight-20)/vb.height);renderSize()};document.getElementById('actual').onclick=()=>{scale=1;renderSize()};document.getElementById('plus').onclick=()=>{scale=Math.min(4,scale*1.2);renderSize()};document.getElementById('minus').onclick=()=>{scale=Math.max(.15,scale/1.2);renderSize()};
function save(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}async function svgFor(m){if(!Object.hasOwn(FILES,m))throw Error('视图不在固定白名单');const r=await fetch(FILES[m],{cache:'no-store'});if(!r.ok)throw Error('SVG读取失败');return await r.text()}async function downloadSvg(m){save(new Blob([await svgFor(m)],{type:'image/svg+xml;charset=utf-8'}),m==='full'?'ZK0003-完整示图.svg':'ZK0003-0至45米详图.svg')}async function downloadPng(m){const text=await svgFor(m),url=URL.createObjectURL(new Blob([text],{type:'image/svg+xml;charset=utf-8'})),img=new Image();img.onload=()=>{const k=Math.min(3,12000/img.width,12000/img.height,Math.sqrt(64000000/(img.width*img.height))),c=document.createElement('canvas');c.width=Math.floor(img.width*k);c.height=Math.floor(img.height*k);const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{if(b)save(b,m==='full'?'ZK0003-完整示图-高清.png':'ZK0003-0至45米详图-高清.png');URL.revokeObjectURL(url)},'image/png')};img.onerror=()=>{URL.revokeObjectURL(url);setStatus('PNG生成失败，请下载SVG查看')};img.src=url}document.getElementById('svgFull').onclick=()=>downloadSvg('full');document.getElementById('svgDetail').onclick=()=>downloadSvg('detail');document.getElementById('pngFull').onclick=()=>downloadPng('full');document.getElementById('pngDetail').onclick=()=>downloadPng('detail');window.addEventListener('resize',()=>{if(scale<1)renderSize()});loadView('full');
</script></body></html>'''
p.write_text(html,encoding='utf-8')
